version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: biblioteca_jogos
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:3306
    command:
      - --default-time-zone=+00:00
      - --sql-require-primary-key=ON
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
